//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageSentByFax
    {
        public int Id { get; set; }
        public long userId { get; set; }
        public System.DateTime createdDate { get; set; }
        public string messageId { get; set; }
        public string messageStatus { get; set; }
        public string recipientFaxNumber { get; set; }
    }
}
