//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricingPlan
    {
        public int Id { get; set; }
        public string PlanName { get; set; }
        public string Description { get; set; }
        public decimal MonthlyPrice { get; set; }
        public decimal AnnuallyPrice { get; set; }
        public string PromotionCode { get; set; }
        public Nullable<int> PromoBasePlanId { get; set; }
        public Nullable<System.DateTime> PromoAvailabilityStartDate { get; set; }
        public Nullable<System.DateTime> PromoAvailabilityEndDate { get; set; }
        public Nullable<int> PromoDurationAnnually { get; set; }
        public Nullable<int> PromoDurationMonthly { get; set; }
    }
}
