//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customers
    {
        public int Customer_Id { get; set; }
        public int User_Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string SocialSecurityNo { get; set; }
        public string Gender { get; set; }
        public string Race { get; set; }
        public string Ethnicity { get; set; }
        public string LanguageKnown { get; set; }
        public string PrimaryAddress { get; set; }
        public string City { get; set; }
        public Nullable<int> State_Id { get; set; }
        public string StateName { get; set; }
        public string Zipcode { get; set; }
        public string HomePhoneNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public string WorkPhoneNumber { get; set; }
        public string EmailId { get; set; }
        public string MaritalStatus { get; set; }
        public string CitizenshipStatus { get; set; }
    
        public virtual tbl_States tbl_States { get; set; }
    }
}
