//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ailments
    {
        public long ailment_id { get; set; }
        public string ailment_name { get; set; }
        public System.DateTime entry_date { get; set; }
        public System.DateTime change_date { get; set; }
    }
}
