//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer_Providers
    {
        public long provider_id { get; set; }
        public long customer_id { get; set; }
        public string provider_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string specialty { get; set; }
        public string phone { get; set; }
        public string first { get; set; }
        public string last { get; set; }
        public string zip { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string comments { get; set; }
        public System.DateTime entry_date { get; set; }
        public System.DateTime change_date { get; set; }
    }
}
