//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Users()
        {
            this.Files = new HashSet<File>();
            this.UserLogins = new HashSet<UserLogin>();
            this.Roles = new HashSet<Role>();
        }
    
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Organization { get; set; }
        public string PrimaryAddress { get; set; }
        public string City { get; set; }
        public Nullable<int> State_Id { get; set; }
        public string Zipcode { get; set; }
        public string HomePhoneNumber { get; set; }
        public string Status { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public string validation { get; set; }
        public long user_id { get; set; }
        public string SocialSecurityNo { get; set; }
        public string Gender { get; set; }
        public string Race { get; set; }
        public string Ethnicity { get; set; }
        public string LanguageKnown { get; set; }
        public string CellPhoneNumber { get; set; }
        public string WorkPhoneNumber { get; set; }
        public string MaritalStatus { get; set; }
        public string CitizenshipStatus { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string StateName { get; set; }
        public Nullable<int> Plan_Id { get; set; }
        public string MembershipBillingCycle { get; set; }
        public Nullable<System.DateTime> MembershipDueDate { get; set; }
        public string ANetSubscriptionId { get; set; }
        public string ANetCustomerProfileId { get; set; }
        public string ANetCustomerPaymentProfileId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
