//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer_Medications
    {
        public long medication_id { get; set; }
        public long customer_id { get; set; }
        public Nullable<long> provider_id { get; set; }
        public string medication_name { get; set; }
        public string medication_desc { get; set; }
        public string medication_dose { get; set; }
        public string medication_route { get; set; }
        public string medication_frequency { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public System.DateTime entry_date { get; set; }
        public System.DateTime change_date { get; set; }
        public int FIXEDOTC { get; set; }
        public Nullable<bool> OTC { get; set; }
    }
}
