//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InsuranceInfo
    {
        public int InsuranceInfo_Id { get; set; }
        public int Customer_Id { get; set; }
        public string PaymentType { get; set; }
        public string PolicyNumber { get; set; }
        public string PlanType { get; set; }
        public string AuthorizationNumber { get; set; }
        public string SubscriberAddress { get; set; }
        public string City { get; set; }
        public Nullable<int> State_Id { get; set; }
        public string StateName { get; set; }
        public string Zipcode { get; set; }
        public string InsuranceVerificationType { get; set; }
        public string RelationshiptoPatient { get; set; }
    }
}
