//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmergencyContacts
    {
        public int EmergencyContact_Id { get; set; }
        public int Customer_Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string RelationshiptoPatient { get; set; }
        public string ContactAddress { get; set; }
        public string City { get; set; }
        public Nullable<int> State_Id { get; set; }
        public string StateName { get; set; }
        public string Zipcode { get; set; }
        public Nullable<bool> IsSameAsPatientsAddress { get; set; }
        public string HomePhoneNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public string WorkPhoneNumber { get; set; }
        public string IsALegalGuardian { get; set; }
    }
}
