//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UsersHealthRecordsAccess
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public System.DateTime createdDate { get; set; }
        public int accessToken { get; set; }
        public string phraseKey { get; set; }
        public string notifyingEmail { get; set; }
        public string notifyingPerson { get; set; }
    }
}
