//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerStatus
    {
        public int CustomerStatus_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> EmergencyContact_Id { get; set; }
        public Nullable<int> EmployerInfo_Id { get; set; }
        public Nullable<int> InsuranceInfo_Id { get; set; }
        public System.DateTime UpdateTimeStamp { get; set; }
    }
}
