//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployerInfo
    {
        public int EmployerInfo_Id { get; set; }
        public string EmployerName { get; set; }
        public string EmploymentStatus { get; set; }
        public int Customer_Id { get; set; }
    }
}
