//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnifiedhintsEntities : DbContext
    {
        public UnifiedhintsEntities()
            : base("name=UnifiedhintsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileStatu> FileStatus { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<MessageSentByFax> MessageSentByFaxes { get; set; }
        public virtual DbSet<PricingPlan> PricingPlans { get; set; }
        public virtual DbSet<RoleContentAccess> RoleContentAccesses { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<tbl_Ailment_CustSurgeries> tbl_Ailment_CustSurgeries { get; set; }
        public virtual DbSet<tbl_Ailments> tbl_Ailments { get; set; }
        public virtual DbSet<tbl_Assets> tbl_Assets { get; set; }
        public virtual DbSet<tbl_Customer_Ailment> tbl_Customer_Ailment { get; set; }
        public virtual DbSet<tbl_Customer_Allergies> tbl_Customer_Allergies { get; set; }
        public virtual DbSet<tbl_Customer_Medications> tbl_Customer_Medications { get; set; }
        public virtual DbSet<tbl_Customer_Providers> tbl_Customer_Providers { get; set; }
        public virtual DbSet<tbl_Customer_Schedule> tbl_Customer_Schedule { get; set; }
        public virtual DbSet<tbl_Customer_Surgery> tbl_Customer_Surgery { get; set; }
        public virtual DbSet<tbl_Customers> tbl_Customers { get; set; }
        public virtual DbSet<tbl_CustomerStatus> tbl_CustomerStatus { get; set; }
        public virtual DbSet<tbl_DocumentationInfo> tbl_DocumentationInfo { get; set; }
        public virtual DbSet<tbl_EmergencyContacts> tbl_EmergencyContacts { get; set; }
        public virtual DbSet<tbl_EmployerInfo> tbl_EmployerInfo { get; set; }
        public virtual DbSet<tbl_InsuranceInfo> tbl_InsuranceInfo { get; set; }
        public virtual DbSet<tbl_Roles> tbl_Roles { get; set; }
        public virtual DbSet<tbl_States> tbl_States { get; set; }
        public virtual DbSet<tbl_Surgeries> tbl_Surgeries { get; set; }
        public virtual DbSet<tbl_Surgery_CustAilments> tbl_Surgery_CustAilments { get; set; }
        public virtual DbSet<tbl_UserLoginInfo> tbl_UserLoginInfo { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_UsersHealthRecordsAccess> tbl_UsersHealthRecordsAccess { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<tbl_Users_Customers> tbl_Users_Customers { get; set; }
        public virtual DbSet<view_Ailments> view_Ailments { get; set; }
        public virtual DbSet<view_Customer_Ailments> view_Customer_Ailments { get; set; }
        public virtual DbSet<view_Customer_Surgeries> view_Customer_Surgeries { get; set; }
        public virtual DbSet<view_Surgeries> view_Surgeries { get; set; }
    }
}
