//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhintsMvc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Customer_Surgeries
    {
        public Nullable<System.DateTime> end_date { get; set; }
        public System.DateTime start_date { get; set; }
        public string surgery_name { get; set; }
        public long surgery_id { get; set; }
        public string surgery_desc { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long user_id { get; set; }
        public long customer_id { get; set; }
    }
}
